---
server:
  port: 8888
security:
  basic:
    enabled: true
  user:
    name: mike
    password: mike
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/humpmj10/pluralsight-spring-cloudconfig-wa-tolls
#          username: uname
#          password: pass
          search-paths:
          - 'station*'
          repos:
            perf:
              pattern:
              - '*/perf'
              uri: https://github.com/humpmj10/pluralsight-spring-cloudconfig-perf
              search-paths:
                - 'station*'
        encrypt:
          enabled: false